[build]
  publish = "."

[[redirects]]
  from = "/api/intent"
  to = "/.netlify/functions/intent"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
